FROM dunglas/frankenphp:1.10.1-php8.4
LABEL maintainer="Maxence Opigez"

WORKDIR /app

ENV SERVER_NAME=:80
ENV APP_RUNTIME=Runtime\\FrankenPhpSymfony\\Runtime
ENV APP_ENV=dev

RUN apt-get update && apt-get install -qy \
    vim \
    curl \
    wget \
    gnupg \
    git \
    zip \
    unzip \
    && install-php-extensions \
    pdo_mysql \
    sqlite3 \
    intl \
    @composer \
    && rm -rf /var/lib/apt/lists/* \
    # Install Node.js and NPM (version 20.x)
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
